### PR TITLE
Pull dudeofawsomes changes upstream for build compatibility

### PR DESCRIPTION
**Pull request by eliotstocker**

### CODE REVIEW

**Comment by eliotstocker** [comment]
@dudeofawesome what changes are in 486fc40? what is the new expected behaviour?

**Comment by dudeofawesome** [comment]
I messed up with this request. It was trying to figure out how to bring my fork up to date with yours. 

This PR can get closed (I thought I'd already closed it)

**Comment by dudeofawesome** [comment]
I must have accidentally started this PR. It's not quite ready to be merged in yet.

**Comment by dudeofawesome** [comment]
Derp. You opened the request, not me.

486fc40 modifies the way the brightness slider in the Wear app works. Instead of being an absolute slider (which could never reach 100%, at least not on my watch), it is now a relative slider.

It's not quite ready yet though as I haven't tested it with actual lights, nor have it made the UI display the correct values.

I'll take a look at that this weekend and get it ready to be merged in.


All the other commits are just to make the builds not require developer-unique files and bring some dependencies up to date.

**Comment by eliotstocker** [comment]
ill merge thw build updates as im lazy haha, and ill pull the AW update once its done :D

**Comment by dudeofawesome** [comment]
Alright, sounds good. I'll start a PR once it's done

Are there any other changes that haven't been pushed into the Play Store build yet?

**Comment by dudeofawesome** [comment]
Can we close this PR as is, without pulling in 7eb410c or newer, and then open a new one solely about the changes I've made to the brightness slider on the watch? I'd like to discuss it a little bit before we actually merge in.

**Comment by NoonanMedia** [comment]
ok closing now, feel free to open another one

**Comment by dudeofawesome** [comment]
Hey, it looks like you tried to close the PR, but it didn't stick or something
image
Do you think you could try again?

**Comment by dudeofawesome** [comment]
I wanted to write up the PR message, but can't open a new PR, so I'm going to post it here for now. I'll move it over to the new PR once it's open.

##### The main purpose of this PR was to update the brightness slider on the Wear app to act more like a scroll wheel instead of using absolute positioning. 
I couldn't get the brightness to reach 100% using the old system, as well as it being awkward to make slight adjustments.

Now, the brightness slider acts more like a scroll wheel, where the user can drag up and down to relatively adjust the brightness.

I'm not sure what the expected behavior is when the user is on white bulbs. It looks like the original behavior was that the brightness slider simply wouldn't work for them.

##### I also made a few other small tweaks here and there which are outlined below:

* `abc_ic_clear_mtrl_alpha` was missing, so I replaced it with `ic_ab_back_material` (which I believe to be the same icon)
* The Tasker view was still using the old light toggle, so I updated it to use the newer 2 part button (this allows Tasker tasks to immediately turn the light off, instead of having to turn it on first.)
* Removing the 3 dot overflow closing button from the 3 dot overflow to better match the expected behavior.
* Improving the gitignore so that we aren't all committing generated files and having to sift through those
* Bringing the build tools and other dependencies up to date with their latest versions

**Comment by eliotstocker** [comment]
My Bad i was logged in on the wrong account, closing now! :D

**Pull request closed without merging**
