### PR TITLE
Adding ability to disable zones

### PR DESCRIPTION
**Pull request by dudeofawesome**
This includes changes to be able to disable zones. It affects the main app and both widgets.

There are a few minor fixes here and there too.
- Fixed a bunch of typos
- Changed the brightness slider to use the native seekbar instead of a custom implementation.
- Settings page now sets the status bar color properly
- Settings sub-pages now have an action bar, and set their status bar color
- I removed the clock from the large widget. If a user wants a clock widget, they should use a dedicated one.

### CODE REVIEW

**Comment by eliotstocker** [comment]
i like this commit, great work, but before i pull can you revert removing the clock from the widget, the reason for this is that on older versions of android you can only have a single lockscreen widget, and this allows the user to have a clock and light switches.

**Comment by dudeofawesome** [comment]
The reason that I removed the clock widget was in order to add the ability to resize the widget for use with fewer enabled zones. I don't think that we should have the clock on that specific widget, but perhaps we could add another one that has the clock enabled?

Do you know what portion of our install base actually uses lock screen widgets?

**Comment by eliotstocker** [comment]
i don't see a problem with maintaining the clock and having the widget resize, if we must we can make the clock hide once the widget wets bellow a certain width.

it seems to me that there is no good reason to remove functionality as it is not causing any bugs or issues. i dont know the exact install base but i do know we have quite a few users how are bellow 5.0 so i would like to maintain the ability to have the lockscreen widget with the clock

**Comment by dudeofawesome** [comment]
Alright, I'll add that back in.

**Comment by eliotstocker** [comment]
looking forward to it, as soon as thats done, ill merge this in and get prepared for the next beta upload

**Pull request closed without merging**
